# Generated by Django 6.1.1 on 2026-09-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=50)),
                ("applied_date", models.DateField()),
                ("deadline", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
