# Generated by Django 6.0.5 on 2026-09-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_interview"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("college", models.CharField(max_length=150)),
                ("degree", models.CharField(max_length=100)),
                ("cgpa", models.FloatField()),
                ("graduation_year", models.IntegerField()),
            ],
        ),
    ]
