# Generated by Django 6.0.5 on 2026-09-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("level", models.CharField(max_length=50)),
            ],
        ),
    ]
