# Generated by Django 6.1.1 on 2026-09-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0008_skill_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="resumes/"),
        ),
    ]
