# Generated by Django 6.1.1 on 2026-09-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0009_profile_resume"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="category",
            field=models.CharField(default="Programming", max_length=100),
        ),
    ]
